const newNotices=[
['You make time for people.','You used to come all the way to my place almost every day just to spend time with me. You never made a big deal about it, but I noticed how much effort that actually takes. It’s one of those little things about you that I really appreciate.'],
['You’re incredibly kind.','You have a way of being thoughtful without making a whole production out of it. It’s just part of how you are, and I think that’s a pretty wonderful quality to have.'],
['You’re ridiculously easy to talk to.','Important conversations, completely unnecessary conversations, random thoughts, terrible jokes… Somehow, everything is fair game. And I don’t think we’ve ever really run out of things to talk about.'],
['You actually listen.','Like, actually listen. You remember things people tell you, you pay attention, and you make people feel heard. It’s something I really admire about you.'],
['Your patience is slightly ridiculous.','You have an impressive ability to let things take their time without immediately trying to fix everything. I could probably learn a thing or two from you.'],
['You work incredibly hard.','This one genuinely amazes me. I see how much effort you put into the things you care about, and how seriously you take what you’re working towards. I hope you know that it’s something people notice—and something you should be really proud of.'],
['You make Bangalore surprisingly fun.','Somehow, “let’s find somewhere to go this weekend” became a perfectly legitimate weekend activity. Cafés, random places, exploring somewhere new… I’m beginning to think the location wasn’t actually the important part.'],
['You said yes to Coorg.','No further explanation required. A whole weekend away, questionable amounts of food, pretty views and enough memories to make the trip worth it. 10/10 decision. Would recommend repeating.'],
['You became part of my routine very quickly.','Suddenly there was someone to talk to, someone to make weekend plans with, and someone to watch another episode of Game of Thrones with. I still haven’t figured out exactly when that happened.'],
['You make ordinary things more fun.','Getting food. Going somewhere random. Sitting around talking. Watching another episode. Sometimes doing absolutely nothing. You have a talent for making a normal day feel like a day worth remembering.'],
['You have a very good “let’s just do it” energy.','There’s something I really like about the fact that you’re willing to try things, go places and make plans without needing everything to be perfectly figured out first. I hope you keep that part of yourself.'],
['You’re just really lovely to have around.','That’s probably the simplest way I can put it. You’re kind, patient, hardworking, adventurous, ridiculously easy to talk to, and occasionally responsible for making me watch Game of Thrones every single day. It’s a pretty good combination.']
];
function renderNewNotices(){const list=document.getElementById('noticed-list');if(!list)return;list.dataset.refined='yes';list.innerHTML=newNotices.map((n,i)=>`<article class="notice"><span>${String(i+1).padStart(2,'0')}</span><div class="notice-text"><strong>${n[0]}</strong><p>${n[1]}</p></div></article>`).join('');const heading=document.querySelector('#noticed h2');if(heading)heading.textContent='Things I Really Like About You';if(!document.querySelector('.noticed-subtitle'))heading?.insertAdjacentHTML('afterend','<p class="noticed-subtitle">An entirely unbiased list. Probably.</p>');if(!document.querySelector('.noticed-note'))list.insertAdjacentHTML('afterend','<p class="noticed-note"><strong>This list is obviously not exhaustive.</strong><br>I’ve only had two months to collect evidence.<br><strong>Further research is ongoing.</strong></p>')}
window.renderNewNotices=renderNewNotices;renderNewNotices();
