const notices=[
['You used to come all the way to my place almost every day just to spend time with me.','I don’t think you ever made a big deal out of it, but I noticed. I still do. There’s something incredibly sweet about someone choosing to spend their time with you simply because they’d rather be with you.'],
['You somehow made exploring Bangalore on weekends feel like an actual activity.','It didn’t really matter where we went. A new café, a random place neither of us had heard of, or somewhere we probably wouldn’t have gone otherwise — somehow, having you there made it worth going.'],
['You agreed to disappear to Coorg with me for a weekend.','And somewhere between the roads, the views, the conversations and all the little moments in between, that weekend became one of those memories I already know I’ll be particularly fond of.'],
['You became part of my everyday life surprisingly quickly.','Two months isn’t a very long time, and yet somehow there are already so many little parts of my day that feel better when they have you in them. I’m still not entirely sure how you managed that.'],
['You make ordinary plans feel like something worth looking forward to.','I think that’s one of my favourite things about you. Nothing has to be particularly exciting or elaborate. If it’s time with you, somehow an ordinary day starts feeling like it has something special waiting for me.'],
['You’re incredibly easy to talk to.','Somehow, conversations with you never feel like work. I can tell you the important things, the completely insignificant things, and all the random thoughts in between — and you just listen. Being heard by someone is such a quietly beautiful thing.'],
['You have this kind of patience that makes people feel safe around you.','You don’t rush people into having the right words or the right answers. You just give them the space to be themselves. I’ve really come to appreciate that about you.'],
['You’re kind in ways that don’t feel performative.','It’s in the little things, the things you probably don’t even think twice about. And I think that’s what makes your kindness so lovely — it seems to just be a part of who you are.'],
['You have somehow made distance feel both very annoying and very worth fighting with.','I didn’t exactly ask for the LDR chapter this early, but here we are. And apparently, missing you is now a regular part of my personality.'],
['I’ve realised that one of my favourite things about you is simply how comfortable you make it feel to be around you.','No performance. No pretending. Just conversations, stupid jokes, comfortable silences and being ourselves.'],
['I like how quickly you became someone I want to tell things to.','Something happens during my day and, more often than not, there’s this little thought in my head that goes, “I should tell her this.” I don’t think that’s something you can force. It just happens when someone starts becoming important to you.'],
['And perhaps my favourite observation of all: somehow, in a very short amount of time, you’ve become someone I’m incredibly fond of.','And I’m really, really glad you did.']
];
function renderNotices(){const list=document.getElementById('noticed-list');if(!list||list.dataset.refined)return;list.dataset.refined='yes';list.innerHTML=notices.map((n,i)=>`<article class="notice"><span>${String(i+1).padStart(2,'0')}</span><div class="notice-text"><strong>${n[0]}</strong><p>${n[1]}</p></div></article>`).join('')}
renderNotices();
document.addEventListener('click',event=>{const notice=event.target.closest('.notice');if(notice)notice.classList.toggle('open')});
document.querySelectorAll('.notice-text p').forEach(paragraph=>paragraph.style.display='none');document.addEventListener('click',event=>{const notice=event.target.closest('.notice');if(notice){const paragraph=notice.querySelector('.notice-text p');if(paragraph)paragraph.style.display=notice.classList.contains('open')?'block':'none'}});
